spring.application.name=centre-formation

# Active Profile (dev or prod)
# Pour dev (H2): mvn spring-boot:run -Dspring-boot.run.profiles=dev
# Pour prod (MySQL): mvn spring-boot:run -Dspring-boot.run.profiles=prod
spring.profiles.active=dev

# JPA Properties (Common)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging (Common)
logging.level.spring.jpa.centre_formation=INFO
logging.level.org.springframework.security=INFO

# Server
server.port=8082
server.error.include-message=always
server.error.include-binding-errors=always

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json

# Jackson Configuration
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.write-dates-as-timestamps=false

jwt.secret=MySuperSecretKeyThatIsAtLeast32BytesLong
jwt.expiration=172800000

